name: Regular Check
on:
  schedule:
    #Run at 10:10 on Monday.
    - cron: "10 10 * * MON"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run integration tests
        uses: ./.github/actions/integrationTests
